/*
 * Copyright (c) 2023 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_ADC_RENESAS_ADC_B_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_ADC_RENESAS_ADC_B_H_

/* ADC Unit 0 */
#define RENESAS_ADC_B_CH0  0
#define RENESAS_ADC_B_CH1  1
#define RENESAS_ADC_B_CH2  2
#define RENESAS_ADC_B_CH3  3
#define RENESAS_ADC_B_CH4  4
#define RENESAS_ADC_B_CH5  5
#define RENESAS_ADC_B_CH6  6
#define RENESAS_ADC_B_CH7  7

/* ADC Unit 1 & 2 (shared) */
#define RENESAS_ADC_B_CH8  8
#define RENESAS_ADC_B_CH9  9
#define RENESAS_ADC_B_CH10 10
#define RENESAS_ADC_B_CH11 11
#define RENESAS_ADC_B_CH12 12
#define RENESAS_ADC_B_CH13 13
#define RENESAS_ADC_B_CH14 14
#define RENESAS_ADC_B_CH15 15
#define RENESAS_ADC_B_CH16 16
#define RENESAS_ADC_B_CH17 17
#define RENESAS_ADC_B_CH18 18
#define RENESAS_ADC_B_CH19 19
#define RENESAS_ADC_B_CH20 20
#define RENESAS_ADC_B_CH21 21
#define RENESAS_ADC_B_CH22 22
#define RENESAS_ADC_B_CH23 23
#define RENESAS_ADC_B_CH24 24
#define RENESAS_ADC_B_CH25 25
#define RENESAS_ADC_B_CH26 26
#define RENESAS_ADC_B_CH27 27
#define RENESAS_ADC_B_CH28 28
#define RENESAS_ADC_B_CH29 29
#define RENESAS_ADC_B_CH30 30
#define RENESAS_ADC_B_CH31 31
#define RENESAS_ADC_B_CH32 32
#define RENESAS_ADC_B_CH33 33
#define RENESAS_ADC_B_CH34 34
#define RENESAS_ADC_B_CH35 35

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_ADC_SMARTBOND_ADC_H_ */
