/*
 * Copyright (c) 2025 Renesas Electronics Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "udc_common.h"

#include <soc.h>
#include <zephyr/drivers/pinctrl.h>
#include <zephyr/drivers/clock_control/renesas_rx_cgc.h>
#include <zephyr/drivers/usb/udc.h>
#include "r_usb_device.h"

#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(udc_renesas_rx, CONFIG_UDC_DRIVER_LOG_LEVEL);

extern void usb_device_isr(void);

#define UDC_ISR(irq) BSP_ICU_IRQ_HANDLER(irq, usb_device_isr)

struct udc_renesas_rx_config {
	const struct pinctrl_dev_config *pcfg;
	const struct device **clocks;
	size_t num_of_clocks;
	size_t num_of_eps;
	struct udc_ep_config *ep_cfg_in;
	struct udc_ep_config *ep_cfg_out;
	void (*make_thread)(const struct device *dev);
	int speed_idx;
};

struct udc_renesas_rx_data {
	struct k_thread thread_data;
	struct st_usbd_instance_ctrl udc;
	struct st_usbd_cfg udc_cfg;
};

enum udc_renesas_rx_event_type {
	/* An event generated by the HAL driver */
	UDC_RENESAS_RX_EVT_HAL,
	/* Shim driver event to trigger next transfer */
	UDC_RENESAS_RX_EVT_XFER,
	/* Let controller perform status stage */
	UDC_RENESAS_RX_EVT_STATUS,
};

struct udc_renesas_rx_evt {
	enum udc_renesas_rx_event_type type;
	usbd_event_t hal_evt;
	uint8_t ep;
};

K_MSGQ_DEFINE(drv_msgq, sizeof(struct udc_renesas_rx_evt), CONFIG_UDC_RENESAS_RX_MAX_QMESSAGES,
	      sizeof(uint32_t));

static void udc_renesas_rx_event_handler(usbd_callback_arg_t *p_args)
{
	const struct device *dev = p_args->p_context;
	struct udc_renesas_rx_evt evt;

	switch (p_args->event.event_id) {
	case USBD_EVENT_BUS_RESET:
		udc_submit_event(dev, UDC_EVT_RESET, 0);
		break;

	case USBD_EVENT_VBUS_RDY:
		udc_submit_event(dev, UDC_EVT_VBUS_READY, 0);
		break;

	case USBD_EVENT_VBUS_REMOVED:
		udc_submit_event(dev, UDC_EVT_VBUS_REMOVED, 0);
		break;

	case USBD_EVENT_SUSPEND:
		udc_set_suspended(dev, true);
		udc_submit_event(dev, UDC_EVT_SUSPEND, 0);
		break;

	case USBD_EVENT_RESUME:
		udc_set_suspended(dev, false);
		udc_submit_event(dev, UDC_EVT_RESUME, 0);
		break;

	case USBD_EVENT_SOF:
		udc_submit_sof_event(dev);
		break;

	default:
		evt.type = UDC_RENESAS_RX_EVT_HAL;
		evt.hal_evt = p_args->event;
		k_msgq_put(&drv_msgq, &evt, K_NO_WAIT);
		break;
	}
}

static void __maybe_unused udc_renesas_rx_usbi_interrupt_handler(void *arg)
{
	ARG_UNUSED(arg);
	UDC_ISR(DT_IRQ_BY_NAME(DT_NODELABEL(usbfs), usbi, irq))
}

static void __maybe_unused udc_renesas_rx_usbr_interrupt_handler(void *arg)
{
	ARG_UNUSED(arg);
	UDC_ISR(DT_IRQ_BY_NAME(DT_NODELABEL(usbfs), usbr, irq))
}

static void __maybe_unused udc_renesas_rx_interrupt_handler(void *arg)
{
	ARG_UNUSED(arg);
	UDC_ISR(DT_IRQ_BY_NAME(DT_NODELABEL(usbhs), usbhsr, irq));
}

static void udc_event_xfer_next(const struct device *dev, const uint8_t ep)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);
	struct udc_ep_config *ep_cfg = udc_get_ep_cfg(dev, ep);
	struct net_buf *buf;

	if (udc_ep_is_busy(ep_cfg)) {
		return;
	}

	buf = udc_buf_peek(ep_cfg);
	if (buf != NULL) {
		int err;

		err = R_USBD_XferStart(&data->udc, ep, buf->data,
				       USB_EP_DIR_IS_IN(ep) ? buf->len : buf->size);
		if (err != FSP_SUCCESS) {
			LOG_ERR("ep 0x%02x error", ep);
			udc_submit_ep_event(dev, buf, -ECONNREFUSED);
		} else {
			LOG_DBG("ep 0x%02x transfer started, len %u", ep,
				USB_EP_DIR_IS_IN(ep) ? buf->len : buf->size);
			udc_ep_set_busy(ep_cfg, true);
		}
	}
}

static int usbd_ctrl_feed_dout(const struct device *dev, const size_t length)
{
	struct udc_ep_config *cfg = udc_get_ep_cfg(dev, USB_CONTROL_EP_OUT);
	struct net_buf *buf;
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	buf = udc_ctrl_alloc(dev, USB_CONTROL_EP_OUT, length);
	if (buf == NULL) {
		return -ENOMEM;
	}

	k_fifo_put(&cfg->fifo, buf);

	if (FSP_SUCCESS != R_USBD_XferStart(&data->udc, cfg->addr, buf->data, buf->size)) {
		return -EIO;
	}

	LOG_DBG("ep 0x%02x transfer started, len %zu", cfg->addr, length);

	return 0;
}

static void udc_event_xfer_ctrl_in(const struct device *dev, struct net_buf *const buf)
{
	if (udc_ctrl_stage_is_status_in(dev) || udc_ctrl_stage_is_no_data(dev)) {
		/* Status stage finished, notify upper layer */
		udc_ctrl_submit_status(dev, buf);
	}

	/* Update to next stage of control transfer */
	udc_ctrl_update_stage(dev, buf);

	if (udc_ctrl_stage_is_status_out(dev)) {
		/* IN transfer finished, perform status stage OUT and release buffer */
		usbd_ctrl_feed_dout(dev, 0);
		net_buf_unref(buf);
	}
}

static void udc_event_status_in(const struct device *dev)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);
	struct net_buf *buf;

	buf = udc_buf_get(udc_get_ep_cfg(dev, USB_CONTROL_EP_IN));
	if (unlikely(buf == NULL)) {
		LOG_DBG("ep 0x%02x queue is empty", USB_CONTROL_EP_IN);
		return;
	}

	/* Perform status stage IN */
	if (FSP_SUCCESS != R_USBD_XferStart(&data->udc, USB_CONTROL_EP_IN, NULL, 0)) {
		LOG_ERR("Failed to start status IN transfer");
		return;
	}

	LOG_DBG("ep 0x%02x xfer started, len %d", USB_CONTROL_EP_IN, 0);

	udc_event_xfer_ctrl_in(dev, buf);
}

static void udc_event_xfer_ctrl_out(const struct device *dev, struct net_buf *const buf,
				    uint32_t len)
{
	net_buf_add(buf, len);

	if (udc_ctrl_stage_is_status_out(dev)) {
		/* Status stage finished, notify upper layer */
		udc_ctrl_submit_status(dev, buf);
	}

	/* Update to next stage of control transfer */
	udc_ctrl_update_stage(dev, buf);

	if (udc_ctrl_stage_is_status_in(dev)) {
		udc_ctrl_submit_s_out_status(dev, buf);
	}
}

static int udc_event_xfer_setup(const struct device *dev, struct udc_renesas_rx_evt *evt)
{
	struct net_buf *buf;
	int err;

	struct usb_setup_packet *setup_packet =
		(struct usb_setup_packet *)&evt->hal_evt.setup_received;

	buf = udc_ctrl_alloc(dev, USB_CONTROL_EP_OUT, sizeof(struct usb_setup_packet));
	if (buf == NULL) {
		LOG_ERR("Failed to allocate for setup");
		return -ENOMEM;
	}

	udc_ep_buf_set_setup(buf);
	net_buf_add_mem(buf, setup_packet, sizeof(struct usb_setup_packet));

	/* Update to next stage of control transfer */
	udc_ctrl_update_stage(dev, buf);

	if (udc_ctrl_stage_is_data_out(dev)) {
		/*  Allocate and feed buffer for data OUT stage */
		LOG_DBG("s:%p|feed for -out-", buf);
		err = usbd_ctrl_feed_dout(dev, udc_data_stage_length(buf));
		if (err == -ENOMEM) {
			err = udc_submit_ep_event(dev, buf, err);
		}
	} else if (udc_ctrl_stage_is_data_in(dev)) {
		err = udc_ctrl_submit_s_in_status(dev);
	} else {
		err = udc_ctrl_submit_s_status(dev);
		if (err == 0) {
			/* No-data stage, call status in to response to host */
			udc_event_status_in(dev);
		}
	}

	return err;
}

static void udc_event_xfer_complete(const struct device *dev, struct udc_renesas_rx_evt *evt)
{
	struct net_buf *buf;
	struct udc_renesas_rx_data *data = udc_get_private(dev);
	struct udc_ep_config *ep_cfg;

	uint8_t ep = evt->hal_evt.xfer_complete.ep_addr;
	usbd_xfer_result_t result = evt->hal_evt.xfer_complete.result;
	uint32_t len = evt->hal_evt.xfer_complete.len;

	ep_cfg = udc_get_ep_cfg(dev, ep);
	udc_ep_set_busy(ep_cfg, false);

	/* why not buff get */
	buf = udc_buf_peek(ep_cfg);
	if (buf == NULL) {
		return;
	}

	if (result != USBD_XFER_RESULT_SUCCESS) {
		goto error;
	}

	if (USB_EP_DIR_IS_IN(ep) && udc_ep_buf_has_zlp(buf)) {
		/* Send ZLP, notification about transfer complete should come again */
		udc_ep_buf_clear_zlp(buf);
		if (FSP_SUCCESS != R_USBD_XferStart(&data->udc, ep, NULL, 0)) {
			goto error;
		}

		LOG_DBG("ep 0x%02x xfer started, size %d", ep, 0);

		return;
	}

	buf = udc_buf_get(ep_cfg);

	if (ep == USB_CONTROL_EP_IN) {
		udc_event_xfer_ctrl_in(dev, buf);
	} else if (ep == USB_CONTROL_EP_OUT) {
		udc_event_xfer_ctrl_out(dev, buf, len);
	} else {
		if (USB_EP_DIR_IS_OUT(ep)) {
			net_buf_add(buf, len);
		}
		udc_submit_ep_event(dev, buf, 0);
	}

	return;
error:
	LOG_ERR("ep 0x%02x xfer failed", ep);
	udc_submit_ep_event(dev, buf, -EIO);
}

static ALWAYS_INLINE void renesas_rx_thread_handler(void *const arg)
{
	const struct device *dev = (const struct device *)arg;

	LOG_DBG("Driver %p thread started", dev);
	while (true) {
		struct udc_renesas_rx_evt evt;

		k_msgq_get(&drv_msgq, &evt, K_FOREVER);
		switch (evt.type) {
		case UDC_RENESAS_RX_EVT_HAL: {
			switch (evt.hal_evt.event_id) {
			case USBD_EVENT_SETUP_RECEIVED:
				udc_event_xfer_setup(dev, &evt);
				break;

			case USBD_EVENT_XFER_COMPLETE:
				udc_event_xfer_complete(dev, &evt);
				break;

			default:
				/* Other cases were handled inside the callback function */
				break;
			}
			break;
		}

		case UDC_RENESAS_RX_EVT_XFER:
			udc_event_xfer_next(dev, evt.ep);
			break;

		case UDC_RENESAS_RX_EVT_STATUS:
			udc_event_status_in(dev);
			break;

		default:
			break;
		}
	}
}

static int udc_renesas_rx_ep_enqueue(const struct device *dev, struct udc_ep_config *const cfg,
				     struct net_buf *buf)
{
	struct udc_renesas_rx_evt evt = {};

	LOG_DBG("%p enqueue %p", dev, buf);

	udc_buf_put(cfg, buf);

	evt.ep = cfg->addr;
	if (cfg->addr == USB_CONTROL_EP_IN && buf->len == 0) {
		/* Tell controller to perform status IN stage */
		evt.type = UDC_RENESAS_RX_EVT_STATUS;
	} else {
		/* Data process stage */
		evt.type = UDC_RENESAS_RX_EVT_XFER;
	}

	if (cfg->stat.halted) {
		LOG_DBG("ep 0x%02x halted", cfg->addr);
	}

	k_msgq_put(&drv_msgq, &evt, K_NO_WAIT);

	return 0;
}

static int udc_renesas_rx_ep_dequeue(const struct device *dev, struct udc_ep_config *const cfg)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);
	unsigned int lock_key;
	struct net_buf *buf;

	lock_key = irq_lock();

	buf = udc_buf_get_all(cfg);
	if (buf != NULL) {
		udc_submit_ep_event(dev, buf, -ECONNABORTED);
	} else {
		LOG_INF("ep 0x%02x queue is empty", cfg->addr);
	}

	if (FSP_SUCCESS != R_USBD_XferAbort(&data->udc, cfg->addr)) {
		return -EIO;
	}

	udc_ep_set_busy(cfg, false);

	irq_unlock(lock_key);

	return 0;
}

static int udc_renesas_rx_ep_enable(const struct device *dev, struct udc_ep_config *const cfg)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);
	usbd_desc_endpoint_t ep_desc;

	if (USB_EP_GET_IDX(cfg->addr) == 0) {
		return 0;
	}

	ep_desc.bLength = sizeof(struct usb_ep_descriptor);
	ep_desc.bDescriptorType = USB_DESC_ENDPOINT;
	ep_desc.bEndpointAddress = cfg->addr;
	ep_desc.bmAttributes = cfg->attributes;
	ep_desc.wMaxPacketSize = cfg->mps;
	ep_desc.bInterval = cfg->interval;

	if (FSP_SUCCESS != R_USBD_EdptOpen(&data->udc, &ep_desc)) {
		LOG_ERR("Failed to enable ep 0x%02x", cfg->addr);
		return -EIO;
	}

	LOG_DBG("Enabled ep 0x%02x", cfg->addr);

	return 0;
}

static int udc_renesas_rx_ep_disable(const struct device *dev, struct udc_ep_config *const cfg)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	if (USB_EP_GET_IDX(cfg->addr) == 0) {
		return 0;
	}

	if (FSP_SUCCESS != R_USBD_EdptClose(&data->udc, cfg->addr)) {
		return -EIO;
	}

	LOG_DBG("Disabled ep 0x%02x", cfg->addr);

	return 0;
}

static int udc_renesas_rx_ep_set_halt(const struct device *dev, struct udc_ep_config *const cfg)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	LOG_DBG("Set halt ep 0x%02x", cfg->addr);

	if (FSP_SUCCESS != R_USBD_EdptStall(&data->udc, cfg->addr)) {
		return -EIO;
	}

	cfg->stat.halted = true;

	return 0;
}

static int udc_renesas_rx_ep_clear_halt(const struct device *dev, struct udc_ep_config *const cfg)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	LOG_DBG("Clear halt ep 0x%02x", cfg->addr);

	if (FSP_SUCCESS != R_USBD_EdptClearStall(&data->udc, cfg->addr)) {
		return -EIO;
	}

	cfg->stat.halted = false;

	return 0;
}

static int udc_renesas_rx_set_address(const struct device *dev, const uint8_t addr)
{
	/* The USB controller will automatically perform a response to the SET_ADRRESS request. */
	LOG_DBG("Set new address %u for %p", addr, dev);

	return 0;
}

static int udc_renesas_rx_host_wakeup(const struct device *dev)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	if (FSP_SUCCESS != R_USBD_RemoteWakeup(&data->udc)) {
		LOG_ERR("Host wakeup FAILED");
		return -EIO;
	}

	LOG_DBG("Remote wakeup from %p", dev);

	return 0;
}

static enum udc_bus_speed udc_renesas_rx_device_speed(const struct device *dev)
{
	struct udc_data *data = dev->data;

	return data->caps.hs ? UDC_BUS_SPEED_HS : UDC_BUS_SPEED_FS;
}

static int udc_renesas_rx_test_mode(const struct device *dev, const uint8_t mode, const bool dryrun)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);
	usbd_test_mode_t hal_test_mode;
	int err;

	switch (mode) {
	case USB_SFS_TEST_MODE_J:
		hal_test_mode = USBD_TEST_MODE_J;
		break;
	case USB_SFS_TEST_MODE_K:
		hal_test_mode = USBD_TEST_MODE_K;
		break;
	case USB_SFS_TEST_MODE_SE0_NAK:
		hal_test_mode = USBD_TEST_MODE_SE0_NAK;
		break;
	case USB_SFS_TEST_MODE_PACKET:
		hal_test_mode = USBD_TEST_MODE_PACKET;
		break;
	default:
		LOG_ERR("Unsupported test mode %u", mode);
		return -EINVAL;
	}

	if (dryrun) {
		LOG_DBG("Test Mode %u supported", mode);
		return 0;
	}

	err = R_USBD_Testmode(&data->udc, hal_test_mode);
	if (err == FSP_ERR_UNSUPPORTED) {
		LOG_ERR("Test mode is not supported in this device");
		return -ENOTSUP;
	}
	if (err != FSP_SUCCESS) {
		LOG_ERR("Failed to set test mode %u", mode);
		return -EIO;
	}

	return 0;
}

static int udc_renesas_rx_enable(const struct device *dev)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	if (FSP_SUCCESS != R_USBD_Connect(&data->udc)) {
		return -EIO;
	}

	LOG_DBG("Enable device %p", dev);

	return 0;
}

static int udc_renesas_rx_disable(const struct device *dev)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	if (FSP_SUCCESS != R_USBD_Disconnect(&data->udc)) {
		return -EIO;
	}

	LOG_DBG("Disable device %p", dev);

	return 0;
}

static int udc_renesas_rx_init(const struct device *dev)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	if (FSP_SUCCESS != R_USBD_Open(&data->udc, &data->udc_cfg)) {
		LOG_ERR("Failed to power on USB device");
		return -EIO;
	}

	if (udc_ep_enable_internal(dev, USB_CONTROL_EP_OUT, USB_EP_TYPE_CONTROL, USB_CONTROL_EP_MPS,
				   0)) {
		LOG_ERR("Failed to enable control OUT endpoint");
		return -EIO;
	}

	if (udc_ep_enable_internal(dev, USB_CONTROL_EP_IN, USB_EP_TYPE_CONTROL, USB_CONTROL_EP_MPS,
				   0)) {
		LOG_ERR("Failed to enable control IN endpoint");
		return -EIO;
	}

#if DT_HAS_COMPAT_STATUS_OKAY(renesas_rx_usbhs)
	if (data->udc_cfg.hs_irq != (IRQn_Type)BSP_IRQ_DISABLED) {
		irq_enable(data->udc_cfg.hs_irq);
	}
#endif

	if (data->udc_cfg.irq != (IRQn_Type)BSP_IRQ_DISABLED) {
		irq_enable(data->udc_cfg.irq);
	}

	if (data->udc_cfg.irq_r != (IRQn_Type)BSP_IRQ_DISABLED) {
		irq_enable(data->udc_cfg.irq_r);
	}

	return 0;
}

static int udc_renesas_rx_shutdown(const struct device *dev)
{
	struct udc_renesas_rx_data *data = udc_get_private(dev);

	if (udc_ep_disable_internal(dev, USB_CONTROL_EP_OUT)) {
		LOG_ERR("Failed to disable control OUT endpoint");
		return -EIO;
	}

	if (udc_ep_disable_internal(dev, USB_CONTROL_EP_IN)) {
		LOG_ERR("Failed to disable control IN endpoint");
		return -EIO;
	}

	if (FSP_SUCCESS != R_USBD_Close(&data->udc)) {
		return -EIO;
	}

	return 0;
}

static int udc_renesas_rx_clock_check(const struct device *dev)
{
	const struct udc_renesas_rx_config *config = dev->config;

#if USBHS_PHY_CLOCK_SOURCE_IS_XTAL
	if (config->speed_idx == UDC_BUS_SPEED_HS) {
		if (BSP_CFG_XTAL_HZ == 0) {
			LOG_ERR("XTAL clock should be provided");
			return -EINVAL;
		}

		return 0;
	}
#endif

	for (size_t i = 0; i < config->num_of_clocks; i++) {
		const struct device *clock_dev = *(config->clocks + i);
		uint32_t clock_rate;

		if (!device_is_ready(clock_dev)) {
			LOG_ERR("%s is not ready", clock_dev->name);
			return -ENODEV;
		}

		clock_control_get_rate(clock_dev, 0, &clock_rate);

		if (strcmp(clock_dev->name, "uclk") == 0 && clock_rate != MHZ(48)) {
			LOG_ERR("Setting for uclk should be 48Mhz");
			return -ENOTSUP;
		}

#if DT_HAS_COMPAT_STATUS_OKAY(renesas_rx_usbhs)
		if (strcmp(clock_dev->name, "usb60clk") == 0 && clock_rate != MHZ(60)) {
			LOG_ERR("Setting for u60clk should be 60Mhz");
			return -ENOTSUP;
		}
#endif
	}

	return 0;
}

static int udc_renesas_rx_driver_preinit(const struct device *dev)
{
	const struct udc_renesas_rx_config *config = dev->config;
	struct udc_renesas_rx_data *priv = udc_get_private(dev);
	struct udc_data *data = dev->data;
	uint16_t mps = 1023;
	int err;

#if !USBHS_PHY_CLOCK_SOURCE_IS_XTAL
	if (priv->udc_cfg.usb_speed == USBD_SPEED_HS) {
		LOG_ERR("High-speed operation is not supported in case PHY clock source is not "
			"XTAL");
		return -ENOTSUP;
	}
#endif

	if (config->speed_idx == UDC_BUS_SPEED_HS) {
		if (!(priv->udc_cfg.usb_speed == USBD_SPEED_HS ||
		      priv->udc_cfg.usb_speed == USBD_SPEED_FS)) {
			LOG_ERR("USBHS module only support high-speed and full-speed device");
			return -ENOTSUP;
		}
	} else {
		/* config->speed_idx == UDC_BUS_SPEED_FS */
		if (priv->udc_cfg.usb_speed != USBD_SPEED_FS) {
			LOG_ERR("USBFS module only support full-speed device");
			return -ENOTSUP;
		}
	}

	err = udc_renesas_rx_clock_check(dev);
	if (err < 0) {
		LOG_ERR("USB Clock check failed");
		return err;
	}

	err = pinctrl_apply_state(config->pcfg, PINCTRL_STATE_DEFAULT);
	if (err < 0) {
		LOG_ERR("Failed to apply pinctrl state");
		return err;
	}

	k_mutex_init(&data->mutex);

	data->caps.rwup = true;
	data->caps.mps0 = UDC_MPS0_64;
	if (priv->udc_cfg.usb_speed == USBD_SPEED_HS) {
		data->caps.hs = true;
		mps = 1024;
	}

	for (int i = 0; i < config->num_of_eps; i++) {
		config->ep_cfg_out[i].caps.out = 1;
		if (i == 0) {
			config->ep_cfg_out[i].caps.control = 1;
			config->ep_cfg_out[i].caps.mps = 64;
		} else {
			config->ep_cfg_out[i].caps.bulk = 1;
			config->ep_cfg_out[i].caps.interrupt = 1;
			config->ep_cfg_out[i].caps.iso = 1;
			config->ep_cfg_out[i].caps.mps = mps;
		}

		config->ep_cfg_out[i].addr = USB_EP_DIR_OUT | i;
		err = udc_register_ep(dev, &config->ep_cfg_out[i]);
		if (err != 0) {
			LOG_ERR("Failed to register endpoint");
			return err;
		}
	}

	for (int i = 0; i < config->num_of_eps; i++) {
		config->ep_cfg_in[i].caps.in = 1;
		if (i == 0) {
			config->ep_cfg_in[i].caps.control = 1;
			config->ep_cfg_in[i].caps.mps = 64;
		} else {
			config->ep_cfg_in[i].caps.bulk = 1;
			config->ep_cfg_in[i].caps.interrupt = 1;
			config->ep_cfg_in[i].caps.iso = 1;
			config->ep_cfg_in[i].caps.mps = mps;
		}

		config->ep_cfg_in[i].addr = USB_EP_DIR_IN | i;
		err = udc_register_ep(dev, &config->ep_cfg_in[i]);
		if (err != 0) {
			LOG_ERR("Failed to register endpoint");
			return err;
		}
	}

	config->make_thread(dev);

	return 0;
}

static void udc_renesas_rx_lock(const struct device *dev)
{
	udc_lock_internal(dev, K_FOREVER);
}

static void udc_renesas_rx_unlock(const struct device *dev)
{
	udc_unlock_internal(dev);
}

static const struct udc_api udc_renesas_rx_api = {
	.lock = udc_renesas_rx_lock,
	.unlock = udc_renesas_rx_unlock,
	.device_speed = udc_renesas_rx_device_speed,
	.init = udc_renesas_rx_init,
	.enable = udc_renesas_rx_enable,
	.disable = udc_renesas_rx_disable,
	.shutdown = udc_renesas_rx_shutdown,
	.set_address = udc_renesas_rx_set_address,
	.host_wakeup = udc_renesas_rx_host_wakeup,
	.ep_enable = udc_renesas_rx_ep_enable,
	.ep_disable = udc_renesas_rx_ep_disable,
	.ep_set_halt = udc_renesas_rx_ep_set_halt,
	.ep_clear_halt = udc_renesas_rx_ep_clear_halt,
	.ep_enqueue = udc_renesas_rx_ep_enqueue,
	.ep_dequeue = udc_renesas_rx_ep_dequeue,
	.ep_try_config = NULL,
	.test_mode = udc_renesas_rx_test_mode,
};

#define DT_DRV_COMPAT renesas_rx_udc

#define USB_RENESAS_RX_MODULE_NUMBER(id) (DT_REG_ADDR(id) == R_USB_FS0_BASE ? 0 : 1)

#define USB_RENESAS_RX_IRQ_GET(id, name, cell)                                                     \
	COND_CODE_1(DT_IRQ_HAS_NAME(id, name), (DT_IRQ_BY_NAME(id, name, cell)),                   \
		    ((IRQn_Type) BSP_IRQ_DISABLED))

#define USB_RENESAS_RX_MAX_SPEED_IDX(id)                                                           \
	(DT_NODE_HAS_COMPAT(id, renesas_rx_usbhs) ? UDC_BUS_SPEED_HS : UDC_BUS_SPEED_FS)

#define USB_RENESAS_RX_SPEED_IDX(id)                                                               \
	COND_CODE_1(CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED,                                  \
			(DT_NODE_HAS_COMPAT(id, renesas_rx_usbhs)                                  \
			? DT_ENUM_IDX_OR(id, maximum_speed, UDC_BUS_SPEED_HS)                      \
			: DT_ENUM_IDX_OR(id, maximum_speed, UDC_BUS_SPEED_FS)),                    \
			(UDC_BUS_SPEED_FS))

#define USB_RENESAS_RX_IRQ_CONNECT(n)                                                              \
	COND_CODE_1(DT_NODE_HAS_COMPAT(DT_INST_PARENT(n), renesas_rx_usbhs),                       \
		    (                                                                              \
			IRQ_CONNECT(DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbhsr, irq),                \
				    DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbhsr, priority),           \
				    udc_renesas_rx_interrupt_handler, DEVICE_DT_INST_GET(n), 0);   \
		    ),                                                                             \
		    (                                                                              \
			int usbi_irq = DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbi, irq);               \
                                                                                                   \
			if (usbi_irq >= 128 && usbi_irq < 144) {                                   \
				R_ICU->SLIXR[usbi_irq - 128].SLIXR = ICU_EVENT_USB0_STATUS;        \
			} else if (usbi_irq >= 144) {                                              \
				R_ICU->SLIR[usbi_irq - 144].SLIR = ICU_EVENT_USB0_STATUS;          \
			}                                                                          \
                                                                                                   \
			IRQ_CONNECT(DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbi, irq),                  \
				DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbi, priority),                 \
				udc_renesas_rx_usbi_interrupt_handler, DEVICE_DT_INST_GET(n), 0);  \
			IRQ_CONNECT(DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbr, irq),                  \
				DT_IRQ_BY_NAME(DT_INST_PARENT(n), usbr, priority),                 \
				udc_renesas_rx_usbr_interrupt_handler, DEVICE_DT_INST_GET(n), 0);  \
		    )                                                                              \
		   )

#define USB_RENESAS_RX_CLOCKS_GET(idx, id)                                                         \
	DEVICE_DT_GET_OR_NULL(DT_PHANDLE_BY_IDX(id, phys_clock, idx))

#define USB_RENESAS_RX_CLOCKS_DEV(n)                                                               \
	LISTIFY(DT_PROP_LEN_OR(DT_INST_PARENT(n), phys_clock, 0),                                  \
			USB_RENESAS_RX_CLOCKS_GET, (,), DT_INST_PARENT(n))

#define UDC_RENESAS_RX_DEVICE_DEFINE(n)                                                            \
	PINCTRL_DT_DEFINE(DT_INST_PARENT(n));                                                      \
	K_THREAD_STACK_DEFINE(udc_renesas_rx_stack_##n, CONFIG_UDC_RENESAS_RX_STACK_SIZE);         \
                                                                                                   \
	static const struct device *udc_renesas_rx_clock_dev_##n[] = {                             \
		USB_RENESAS_RX_CLOCKS_DEV(n)};                                                     \
                                                                                                   \
	static void udc_renesas_rx_thread_##n(void *dev, void *arg1, void *arg2)                   \
	{                                                                                          \
		renesas_rx_thread_handler(dev);                                                    \
	}                                                                                          \
                                                                                                   \
	static void udc_renesas_rx_make_thread_##n(const struct device *dev)                       \
	{                                                                                          \
		struct udc_renesas_rx_data *priv = udc_get_private(dev);                           \
                                                                                                   \
		k_thread_create(&priv->thread_data, udc_renesas_rx_stack_##n,                      \
				K_THREAD_STACK_SIZEOF(udc_renesas_rx_stack_##n),                   \
				udc_renesas_rx_thread_##n, (void *)dev, NULL, NULL,                \
				K_PRIO_COOP(CONFIG_UDC_RENESAS_RX_THREAD_PRIORITY), K_ESSENTIAL,   \
				K_NO_WAIT);                                                        \
		k_thread_name_set(&priv->thread_data, dev->name);                                  \
	}                                                                                          \
                                                                                                   \
	static struct udc_ep_config ep_cfg_in##n[DT_PROP(DT_INST_PARENT(n), num_bidir_endpoints)]; \
	static struct udc_ep_config                                                                \
		ep_cfg_out##n[DT_PROP(DT_INST_PARENT(n), num_bidir_endpoints)];                    \
                                                                                                   \
	static const struct udc_renesas_rx_config udc_renesas_rx_config_##n = {                    \
		.pcfg = PINCTRL_DT_DEV_CONFIG_GET(DT_INST_PARENT(n)),                              \
		.clocks = udc_renesas_rx_clock_dev_##n,                                            \
		.num_of_clocks = DT_PROP_LEN_OR(DT_INST_PARENT(n), phys_clock, 0),                 \
		.num_of_eps = DT_PROP(DT_INST_PARENT(n), num_bidir_endpoints),                     \
		.ep_cfg_in = ep_cfg_in##n,                                                         \
		.ep_cfg_out = ep_cfg_out##n,                                                       \
		.make_thread = udc_renesas_rx_make_thread_##n,                                     \
		.speed_idx = USB_RENESAS_RX_MAX_SPEED_IDX(DT_INST_PARENT(n)),                      \
	};                                                                                         \
                                                                                                   \
	static struct udc_renesas_rx_data udc_priv_##n = {                                         \
		.udc_cfg =                                                                         \
			{                                                                          \
				.module_number = USB_RENESAS_RX_MODULE_NUMBER(DT_INST_PARENT(n)),  \
				.usb_speed = USB_RENESAS_RX_SPEED_IDX(DT_INST_PARENT(n)),          \
				.irq = USB_RENESAS_RX_IRQ_GET(DT_INST_PARENT(n), usbi, irq),       \
				.irq_r = USB_RENESAS_RX_IRQ_GET(DT_INST_PARENT(n), usbr, irq),     \
				.hs_irq = USB_RENESAS_RX_IRQ_GET(DT_INST_PARENT(n), usbhsr, irq),  \
				.ipl = USB_RENESAS_RX_IRQ_GET(DT_INST_PARENT(n), usbi, priority),  \
				.ipl_r =                                                           \
					USB_RENESAS_RX_IRQ_GET(DT_INST_PARENT(n), usbr, priority), \
				.hsipl = USB_RENESAS_RX_IRQ_GET(DT_INST_PARENT(n), usbhsr,         \
								priority),                         \
				.p_context = DEVICE_DT_INST_GET(n),                                \
				.p_callback = udc_renesas_rx_event_handler,                        \
			},                                                                         \
	};                                                                                         \
                                                                                                   \
	static struct udc_data udc_data_##n = {                                                    \
		.mutex = Z_MUTEX_INITIALIZER(udc_data_##n.mutex),                                  \
		.priv = &udc_priv_##n,                                                             \
	};                                                                                         \
                                                                                                   \
	int udc_renesas_rx_driver_preinit##n(const struct device *dev)                             \
	{                                                                                          \
		USB_RENESAS_RX_IRQ_CONNECT(n)                                                      \
		return udc_renesas_rx_driver_preinit(dev);                                         \
	}                                                                                          \
                                                                                                   \
	DEVICE_DT_INST_DEFINE(n, udc_renesas_rx_driver_preinit##n, NULL, &udc_data_##n,            \
			      &udc_renesas_rx_config_##n, POST_KERNEL,                             \
			      CONFIG_KERNEL_INIT_PRIORITY_DEVICE, &udc_renesas_rx_api);

DT_INST_FOREACH_STATUS_OKAY(UDC_RENESAS_RX_DEVICE_DEFINE)
